"""
Navigation generator.

Creates the landing page listing all pipelines.

It never modifies the handwritten Sphinx root index (``docs/source/index.md``).
"""

from __future__ import annotations

from pathlib import Path

from .models import Pipeline


AUTO_HEADER = """<!--
AUTO-GENERATED FILE.

Generated by docs/generate_docs.py

Do not edit manually.
-->

"""


def _write(path: Path, text: str) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if path.exists():

        current = path.read_text(
            encoding="utf8",
        )

        if not current.startswith("<!--\nAUTO-GENERATED FILE."):
            return

    path.write_text(
        AUTO_HEADER + text.rstrip() + "\n",
        encoding="utf8",
    )


# ---------------------------------------------------------------------
# Pipelines index
# ---------------------------------------------------------------------


def generate_navigation(
    docs_root: Path,
    pipelines: list[Pipeline],
) -> None:
    """
    Generate the pipelines index page.

    This page is used by Sphinx to build the navigation for all
    available pipelines.
    """

    lines = []

    lines.append("# Pipelines")
    lines.append("")
    lines.append("Documentation for the available Ensembl Genes Nextflow pipelines.")
    lines.append("")
    lines.append("```{toctree}")
    lines.append(":maxdepth: 1")
    lines.append("")

    for pipeline in sorted(
        pipelines,
        key=lambda p: p.name,
    ):
        lines.append(f"{pipeline.name}/README")

    lines.append("```")
    lines.append("")

    _write(
        docs_root / "pipelines" / "index.md",
        "\n".join(lines),
    )
