[mypy]
python_version = 3.13
warn_return_any = true
warn_unused_configs = true
explicit_package_bases = true

[mypy-metadata_app.*]
ignore_missing_imports = false

[mypy-pandas.*]
ignore_missing_imports = true

[mypy-sklearn.*]
ignore_missing_imports = true
